spring.datasource.url=${DB_URL_PREFIX}${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# disable Netflix's built-in GraphiQL UI since:
# 1) it implements caching by default which is a security risk
# 2) it has no API for inserting CSRF tokens programmatically.
dgs.graphql.graphiql.enabled=false