import { readFileSync } from "node:fs";
import path from "node:path";

import babel from "@rolldown/plugin-babel";
import stylexPlugin from "@stylexjs/unplugin";
import react from "@vitejs/plugin-react";
import { esmExternalRequirePlugin } from "rolldown/plugins";
import { defineConfig, type Plugin } from "vite";
import checker from "vite-plugin-checker";

import bundleEntries from "./SinglePageApplicationBundles.ts";

const webFrontend = path.resolve(import.meta.dirname, "src/main/web-frontend");

// Emits the app-wide stylesheet that every page links: the global reset from
// styles.css, which the StyleX plugin then appends all compiled StyleX rules to
// (it targets this asset via cssInjectionTarget below). Emitting it ourselves —
// rather than letting StyleX pick some entry's CSS — gives the global styles a
// dedicated, unambiguous file.
function stylexCssFile(): Plugin {
  return {
    name: "stylex-css-file",
    enforce: "pre", // must emit before the StyleX plugin's generateBundle looks for it
    generateBundle() {
      this.emitFile({
        type: "asset",
        name: "stylex.generated.css",
        source: readFileSync(path.join(webFrontend, "styles.css"), "utf8"),
      });
    },
  };
}

// The StyleX plugin appends its CSS by re-emitting the target asset, and the copy
// gets deduped to "stylex2.generated.css" because the original still holds the name
// at the moment the copy is named. Rename it back in the bundle graph (property
// mutation propagates on both Rollup and Rolldown; re-keying the bundle object does
// not) so ReactPage.kt's fixed link resolves. Deletable if the StyleX plugin ever
// updates the asset in place instead of re-emitting it.
function stableStylexCssName(): Plugin {
  return {
    name: "stable-stylex-css-name",
    enforce: "post",
    generateBundle(_options, bundle) {
      for (const item of Object.values(bundle)) {
        if (
          item.type === "asset" &&
          item.names[0] === "stylex.generated.css"
        ) {
          item.fileName = "stylex.generated.css";
          return;
        }
      }

      this.error("StyleX CSS asset was not emitted");
    },
  };
}

export default defineConfig(({ mode }) => ({
  // Spring Boot serves the emitted files from src/main/resources/static/bundles
  base: "/bundles/",
  plugins: [
    // The production build runs tsc via `npm run build`; this covers watch mode
    // (`npm run watch` passes --mode development)
    mode === "development" && checker({ typescript: true }),
    // Keeps react external (resolved in the browser via the import map emitted by
    // ReactPage.kt) while converting the `require("react")` calls inside CommonJS
    // dependencies like react-relay into imports, which Rolldown otherwise leaves
    // as browser-breaking runtime requires (rolldown.rs/in-depth/bundling-cjs)
    esmExternalRequirePlugin({
      external: [
        "react",
        "react/compiler-runtime",
        "react/jsx-runtime",
        "react-dom",
        "react-dom/client",
      ],
    }),
    stylexCssFile(),
    // React Compiler must see the original component source before other Babel
    // transforms. Relay then rewrites graphql`...` tags into __generated__ imports.
    babel({ plugins: ["babel-plugin-react-compiler", "relay"] }),
    react(),
    stylexPlugin.vite({
      useCSSLayers: true,
      treeshakeCompensation: true,
      aliases: {
        "*": path.join(webFrontend, "*"),
      },
      // All StyleX rules are merged into one payload and appended to the dedicated
      // app-wide stylesheet emitted by stylexCssFile() above
      cssInjectionTarget: (fileName: string) => fileName === "stylex.generated.css",
    }),
    stableStylexCssName(),
  ],
  resolve: {
    // Resolve absolute imports like "pages/HomePage" via tsconfig's paths
    tsconfigPaths: true,
  },
  worker: {
    // The monaco workers pulled in by GraphiQL code-split, which iife (the
    // default) doesn't support
    format: "es",
  },
  build: {
    // The dev watch script overrides this with --outDir to write straight into
    // the build folder Spring serves from (see package.json)
    outDir: "src/main/resources/static/bundles",
    emptyOutDir: true,
    sourcemap: true,
    rolldownOptions: {
      // One entry per SPA defined in spa-route-definitions; the map is generated by
      // `./gradlew generateBundleEntries` from the SpaApplicationDefinitions
      input: Object.fromEntries(
        Object.entries(bundleEntries).map(([id, entryPath]) => [
          id,
          path.resolve(import.meta.dirname, entryPath),
        ]),
      ),
      // The react family is externalized by esmExternalRequirePlugin above
      external: ["sanitize-html", "highlight.js"],
      output: {
        // Stable names: the Kotlin views reference <entry>.bundle.js and <entry>.css
        entryFileNames: "[name].bundle.js",
        chunkFileNames: "[name]-[hash].js",
        assetFileNames: (assetInfo) => {
          const name = assetInfo.names?.[0] ?? "";
          return name.endsWith(".css") ? "[name][extname]" : "[name]-[hash][extname]";
        },
      },
    },
  },
}));
